M48
; DRILL file {KiCad 7.0.1} date Mon Dec 18 14:15:40 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-18T14:15:40-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
%
G90
G05
T1
X6.4567Y-2.9134
X6.4567Y-3.7992
X10.1969Y-2.9134
X10.1969Y-3.7992
T0
M30
