M48
; DRILL file {KiCad 7.0.1} date Sun Dec 17 22:32:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-17T22:32:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
%
G90
G05
T1
X6.4567Y-4.8622
X6.4567Y-5.748
X10.1969Y-4.8622
X10.1969Y-5.748
T0
M30
